title: my log files
email: iustinivan2002@gmail.com
name: Iustin Ivan
description: >- # this means to ignore newlines until "baseurl:"
  Datadump for my thoughts
keywords: [empty]
baseurl:  # the subpath of your site, e.g. /blog
url: "https://log.notiustin.com/" # the base hostname & protocol for your site, e.g. http://example.com
domain: "log.notiustin.com/" # the domain name for your site, e.g. example.com
language: en

analytics:  

paginate: 25
paginate_path: "/page:num/"

comments: false  # enable comments
disqus:          # disqus account

mathjax: true # Mathematics
mermaid: true # Diagrams

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Category settings
jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
